export default {
  REQUEST_DATA: 'REQUEST_DATA',
  DATA_RECEIVED_SUCCESS: 'DATA_RECEIVED_SUCCESS',
  DATA_RECEIVED_FAIL: 'DATA_RECEIVED_FAIL',
  TOGGLE_KIND: 'TOGGLE_KIND',
  TOGGLE_ID: 'TOGGLE_ID',
};
